# Generated by Django 4.1.3 on 2022-11-16 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none given', max_length=30)),
                ('description', models.CharField(default='none given', max_length=150)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(default='none given', max_length=20)),
                ('description', models.CharField(default='none given', max_length=150)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none given', max_length=30)),
                ('description', models.CharField(default='none given', max_length=150)),
                ('Artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jams.artist')),
                ('Genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jams.genre')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
