# Generated by Django 4.1.3 on 2022-11-16 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='Artist',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='Genre',
            new_name='genre',
        ),
    ]
