# Generated by Django 4.1.3 on 2022-11-17 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0004_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist_songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jams.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jams.song')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
